/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CharactersCharacterIdRouteRouteImport } from './routes/characters.$characterId/route'
import { Route as CharactersCharacterIdLoreRouteImport } from './routes/characters.$characterId/lore'
import { Route as CharactersCharacterIdSheetRouteImport } from './routes/characters.$characterId/sheet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharacterIdRouteRoute =
  CharactersCharacterIdRouteRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CharactersCharacterIdLoreRoute =
  CharactersCharacterIdLoreRouteImport.update({
    id: '/lore',
    path: '/lore',
    getParentRoute: () => CharactersCharacterIdRouteRoute,
  } as any)
const CharactersCharacterIdSheetRoute =
  CharactersCharacterIdSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => CharactersCharacterIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/characters/$characterId': typeof CharactersCharacterIdRouteRouteWithChildren
  '/characters/$characterId/lore': typeof CharactersCharacterIdLoreRoute
  '/characters/$characterId/sheet': typeof CharactersCharacterIdSheetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/characters/$characterId': typeof CharactersCharacterIdRouteRouteWithChildren
  '/characters/$characterId/lore': typeof CharactersCharacterIdLoreRoute
  '/characters/$characterId/sheet': typeof CharactersCharacterIdSheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/characters/$characterId': typeof CharactersCharacterIdRouteRouteWithChildren
  '/characters/$characterId/lore': typeof CharactersCharacterIdLoreRoute
  '/characters/$characterId/sheet': typeof CharactersCharacterIdSheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oauth-callback'
    | '/privacy'
    | '/terms'
    | '/characters/$characterId'
    | '/characters/$characterId/lore'
    | '/characters/$characterId/sheet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oauth-callback'
    | '/privacy'
    | '/terms'
    | '/characters/$characterId'
    | '/characters/$characterId/lore'
    | '/characters/$characterId/sheet'
  id:
    | '__root__'
    | '/'
    | '/oauth-callback'
    | '/privacy'
    | '/terms'
    | '/characters/$characterId'
    | '/characters/$characterId/lore'
    | '/characters/$characterId/sheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CharactersCharacterIdRouteRoute: typeof CharactersCharacterIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId/lore': {
      id: '/characters/$characterId/lore'
      path: '/lore'
      fullPath: '/characters/$characterId/lore'
      preLoaderRoute: typeof CharactersCharacterIdLoreRouteImport
      parentRoute: typeof CharactersCharacterIdRouteRoute
    }
    '/characters/$characterId/sheet': {
      id: '/characters/$characterId/sheet'
      path: '/sheet'
      fullPath: '/characters/$characterId/sheet'
      preLoaderRoute: typeof CharactersCharacterIdSheetRouteImport
      parentRoute: typeof CharactersCharacterIdRouteRoute
    }
  }
}

interface CharactersCharacterIdRouteRouteChildren {
  CharactersCharacterIdLoreRoute: typeof CharactersCharacterIdLoreRoute
  CharactersCharacterIdSheetRoute: typeof CharactersCharacterIdSheetRoute
}

const CharactersCharacterIdRouteRouteChildren: CharactersCharacterIdRouteRouteChildren =
  {
    CharactersCharacterIdLoreRoute: CharactersCharacterIdLoreRoute,
    CharactersCharacterIdSheetRoute: CharactersCharacterIdSheetRoute,
  }

const CharactersCharacterIdRouteRouteWithChildren =
  CharactersCharacterIdRouteRoute._addFileChildren(
    CharactersCharacterIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CharactersCharacterIdRouteRoute: CharactersCharacterIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
