import type { Plugin, ResolvedConfig } from "vite";
import { createHash } from "node:crypto";
import { posix } from "node:path";

const SW_URL = "sw.js";

/**
 * Minimal PWA plugin: emits a precaching service worker + copies the
 * webmanifest at build time.
 *
 * Runtime strategy:
 *  - Navigations: network-first, fall back to the precached shell offline.
 *  - Precached assets: stale-while-revalidate.
 *  - Non-GET and cross-origin requests (Drive REST, /api on prod is
 *    same-origin but keep it safe) pass through untouched.
 *
 * Hand-rolled instead of vite-plugin-pwa: fewer moving parts, no workbox
 * peer-dependency risk on Vite 8.
 */
export function pwaPlugin(): Plugin {
  let config: ResolvedConfig | null = null;

  return {
    name: "charasheet-pwa",
    apply: "build",
    enforce: "post",

    configResolved(resolved) {
      config = resolved;
    },

    async generateBundle(_options, bundle) {
      if (!config) return;
      const base = config.base || "/";

      const urls = new Set<string>();
      for (const fileName of Object.keys(bundle)) {
        if (fileName.endsWith(".map")) continue;
        // Every emitted asset (chunk, css, images, manifest, icons) is
        // either content-hashed or effectively immutable → precache.
        if (fileName.endsWith(".html") || fileName.startsWith("assets/") || fileName === "manifest.webmanifest" || /\.(png|ico|svg|webmanifest)$/.test(fileName)) {
          urls.add(posix.join(base, fileName));
        }
      }

      // The SW itself is generated with a build-time version stamp; index.html
      // is precached under its URL directly.
      urls.add(posix.join(base, "index.html"));

      const files = [...urls].sort();
      // Content-hash the precache list: byte-identical shells keep the same
      // VERSION, so idle deploys don't trigger a pointless re-precache, and
      // lexicographic cache-name ordering (used by activate) still reflects
      // actual deploy order.
      const version = createHash("sha256").update(JSON.stringify(files)).digest("hex").slice(0, 12);
      this.emitFile({
        type: "asset",
        fileName: SW_URL,
        source: renderSw(files, base, version),
      });
    },
  };
}

function renderSw(urls: string[], base: string, version: string): string {
  const scope = base.endsWith("/") ? base : base + "/";
  return `// Generated by scripts/pwa-plugin.ts at build time — do not edit.
const VERSION = ${JSON.stringify(version)};
const SCOPE = ${JSON.stringify(scope)};
const PRECACHE = "precache-" + VERSION;
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(PRECACHE);
      // cache: "reload" bypasses the HTTP cache so precache never poisons itself.
      await Promise.allSettled(
        PRECACHE_URLS.map((url) => cache.add(new Request(url, { cache: "reload" }))),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      // Always retain the cache this SW just installed (PRECACHE), plus the
      // most recent other precache so an open tab mid-session can still
      // lazily import chunks from the previous deploy's shell. Everything
      // else gets evicted.
      const precaches = (await caches.keys()).filter((key) =>
        key.startsWith("precache-"),
      );
      const keep = new Set([PRECACHE]);
      const others = precaches.filter((key) => key !== PRECACHE);
      if (others.length > 0) keep.add(others[others.length - 1]);
      for (const key of precaches) {
        if (!keep.has(key)) await caches.delete(key);
      }
      for (const key of await caches.keys()) {
        if (!key.startsWith("precache-")) await caches.delete(key);
      }
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // The token proxy is same-origin in prod and must never be served from,
  // or written to, a cache.
  if (url.pathname.startsWith(SCOPE + "api/")) return;

  if (req.mode === "navigate") {
    event.respondWith(
      (async () => {
        // Bound the network attempt: a hanging connection shouldn't stall
        // page loads when a cached shell is available. Plain JS — this
        // template is emitted verbatim, no TS transpile.
        const timeout = new Promise((resolve) =>
          setTimeout(resolve, 3000, undefined),
        );
        try {
          return await Promise.race([fetch(req), timeout]).then(
            (response) => response ?? caches.match(${JSON.stringify(scope + "index.html")}).then((shell) => shell ?? Response.error()),
          );
        } catch {
          return (
            (await caches.match(${JSON.stringify(scope + "index.html")})) ??
            Response.error()
          );
        }
      })(),
    );
    return;
  }

  // Same-origin static asset from the precache list: stale-while-revalidate.
  // One fetch serves both the page and the cache refresh (clone).
  const swrUrl = PRECACHE_URLS.includes(url.pathname) ? url.pathname : null;
  if (!swrUrl) return;

  event.respondWith(
    (async () => {
      const cached = await caches.match(swrUrl);
      if (cached) {
        // Classic SWR: serve the cached copy immediately; refresh runs
        // detached so first-paint never waits on the network.
        void fetch(swrUrl)
          .then((response) => {
            if (response && response.status === 200) {
              caches.open(PRECACHE).then((cache) => cache.put(swrUrl, response.clone()));
            }
          })
          .catch(() => undefined);
        return cached;
      }
      // Nothing cached yet: fetch, populate, return.
      const response = await fetch(swrUrl);
      if (response && response.status === 200) {
        caches
          .open(PRECACHE)
          .then((cache) => cache.put(swrUrl, response.clone()));
      }
      return response;
    })(),
  );
});
`;
}